### ISSUE TITLE
improve perfomance

### ISSUE THREAD

**Issue by s1r1m1r1** [RafaelBarbosatec/a_star#1]
https://github.com/Sproute777/a_star/tree/feature/a_star_for_tbs

change Offset to Point<int> , no needed to translate toDouble and back, no needed to use floor and etc.

**Comment by RafaelBarbosatec** [comment]
Great!
I will appreciate so much a PR with your contribution.

**Comment by s1r1m1r1** [comment]
for check
-   items.any() items.contains()   more faster then items.where, items.firstWhere
   
-   for (var item in items)  more faster then items.forEach();


indexWhere useful for check item and using it next;

**Comment by RafaelBarbosatec** [comment]
Thanks so much for this tips. I will implement this improvements.

**Comment by s1r1m1r1** [comment]
resolve and merge with 0.3.1
ready for review
added benchmark in example
