### ISSUE TITLE
AI search targets,allies

### ISSUE THREAD

**Issue by s1r1m1r1** [RafaelBarbosatec/a_star#3]
if you want use AI search path,enemies,allies, maybe need search with options .
For example nearest target or ally, perhaps search target(as item like chest,coins,weapons).

**Comment by RafaelBarbosatec** [comment]
So, the purpose of this package is only give a A* algorithm. Maybe this ideia could be a new package tht use this package.

**Comment by s1r1m1r1** [comment]
> So, the purpose of this package is only give a A* algorithm. Maybe this ideia could be a new package tht use this package.

but create grid is reusing in other type of search,
  maybe diffrent packages for Grid , AStar , tbs finding, ai search

**Comment by Sproute777** [comment]
> So, the purpose of this package is only give a A* algorithm. Maybe this ideia could be a new package tht use this package.
<img width="814" alt="Снимок экрана 2023-09-25 в 05 36 41" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/720baf8c-db5d-4e83-b98a-409fc09429c4">
<img width="814" alt="Снимок экрана 2023-09-25 в 05 37 30" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/fa1b11c8-3d92-4d34-8434-75f08e3623ed">

some example extension optimization when u import only one and two funtions

**Comment by Sproute777** [comment]
Astart+ findPath + findSteps this is 16 kb
Astar + findPath 14kb
why need more packages for search algoritmis ?
