### ISSUE TITLE
step area finding for Turn based games like rpg and etc

### ISSUE THREAD

**Issue by s1r1m1r1** [RafaelBarbosatec/a_star#4]
<img width="796" alt="Снимок экрана 2023-09-21 в 19 59 59" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/e3f55ba3-631e-4f91-9b63-7714bb4e56cb">

**Comment by Sproute777** [comment]
i think there are not needed to use targets in search, maybe best choise set barriers for targets and set tile for path finding traget(-1 tile after get result)
