### ISSUE TITLE
🔥improve search  x10 faster

### ISSUE THREAD

**Issue by s1r1m1r1** [RafaelBarbosatec/a_star#6]
<img width="804" alt="Снимок экрана 2023-09-24 в 13 18 02" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/d79b441c-59b4-459c-910b-9166819f6b7b">

great improve perfomance

**Comment by Sproute777** [comment]
``` dart

/// Calculates the distance g and h
  void _analiseDistance(Tile current, Tile end, {required Tile parent}) {
    current.parent = parent;
    current.g = parent.g + current.weight;
    current.h = _distance(parent, end);
  }

  /// Calculates the distance between two tiles.
  int _distance(Tile tile1, Tile tile2) {
    int distX = (tile1.position.x - tile2.position.x).abs();
    int distY = (tile1.position.y - tile2.position.y).abs();
    return distX * distY; /// <---- this for tiles which have not diagonals
  }

  ```

**Comment by Sproute777** [comment]
for tiles with diagonals 
maybe something like this
distX + distY *  1.42;

**Comment by Sproute777** [comment]
<img width="821" alt="Снимок экрана 2023-09-24 в 13 46 26" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/b1962ff6-e300-49a5-a07c-a0e0b9337667">

have troble because diagonal have some host like straigt

**Comment by Sproute777** [comment]
have any mark for diagonaled tiles

**Comment by Sproute777** [comment]
http://theory.stanford.edu/~amitp/GameProgramming/Heuristics.html
maybe some from this

**Comment by s1r1m1r1** [comment]
<img width="792" alt="Снимок экрана 2023-09-24 в 17 14 48" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/29b459d3-9bc4-4997-b1bb-1ec0287dd2e6">
fixed

**Comment by s1r1m1r1** [comment]
incorrect using parent for calculate distance h

current ,end (correct)

_doneList sometimes strange (but it is fast)
last version calculation 

200-1000microsec vs 1000-60000microsec (sometimes it not the best way ) but resourses usage is super low

**Comment by s1r1m1r1** [comment]
<img width="793" alt="Снимок экрана 2023-09-24 в 18 55 30" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/fc7362b7-a2a2-481f-846a-6190001d82cc">



if you need fastest search , but not  shortest way

**Comment by s1r1m1r1** [comment]
<img width="793" alt="Снимок экрана 2023-09-24 в 19 27 03" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/0991ebf8-7db6-4318-a7f3-832eef9ecb1d">
<img width="793" alt="Снимок экрана 2023-09-24 в 19 27 21" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/59236dd8-bbfc-44ae-bc69-2f8a06a86921">
<img width="793" alt="Снимок экрана 2023-09-24 в 19 27 34" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/9c5344c0-0bd2-48bb-9b71-69d3bfbe3f33">

**Comment by Sproute777** [comment]
<img width="793" alt="Снимок экрана 2023-09-24 в 19 55 42" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/f81ee2f5-5bc9-405b-8d76-903bfc8887ee">
<img width="793" alt="Снимок экрана 2023-09-24 в 19 55 51" src="https://github.com/RafaelBarbosatec/a_star/assets/76906744/66f0d7ef-0692-4e92-b3b3-a33ae5d884f5">

**Comment by s1r1m1r1** [comment]
has some not optimal search

not good for diagonals 

very good for game with mass count npc

**Comment by s1r1m1r1** [comment]
10x faster stable correct search

**Comment by RafaelBarbosatec** [comment]
Good work! 🚀🚀🎉🎉
